server:
  port: 8092

spring:
  application:
    name: ApiGateway
#  security:
#    user:
#      name: admin
#      password: admin
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
      - id: studentms
        uri: lb://studentms
        predicates:
        - Path=/api/v1/student/**
      - id: feesms
        uri: lb://feesms
        predicates:
        - Path=/api/v1/fee/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    